'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
    async up(queryInterface, Sequelize) {
        /**
         * Add seed commands here.
         *
         * Example:
         * await queryInterface.bulkInsert('People', [{
         *   nama: 'John Doe',
         *   isBetaMember: false
         * }], {});
        */
        const desa = [
            { nama: 'Sumber Agung', kecamatan_id: 1, created_at: new Date(), updated_at: new Date() },
            { nama: 'Purbo Sembodo', kecamatan_id: 1, created_at: new Date(), updated_at: new Date() },
            { nama: 'Kibang', kecamatan_id: 1, created_at: new Date(), updated_at: new Date() },
            { nama: 'Margo Jaya', kecamatan_id: 1, created_at: new Date(), updated_at: new Date() },
            { nama: 'Margo Toto', kecamatan_id: 1, created_at: new Date(), updated_at: new Date() },
            { nama: 'Margo Sari', kecamatan_id: 1, created_at: new Date(), updated_at: new Date() },
            { nama: 'Jaya Asri', kecamatan_id: 1, created_at: new Date(), updated_at: new Date() },

            { nama: 'Buana Sakti', kecamatan_id: 2, created_at: new Date(), updated_at: new Date() },
            { nama: 'Balai Kencono', kecamatan_id: 2, created_at: new Date(), updated_at: new Date() },
            { nama: 'Rejo Agung', kecamatan_id: 2, created_at: new Date(), updated_at: new Date() },
            { nama: 'Adi Warno', kecamatan_id: 2, created_at: new Date(), updated_at: new Date() },
            { nama: 'Nampi Rejo', kecamatan_id: 2, created_at: new Date(), updated_at: new Date() },
            { nama: 'Banar Joyo', kecamatan_id: 2, created_at: new Date(), updated_at: new Date() },
            { nama: 'Telogo Rejo', kecamatan_id: 2, created_at: new Date(), updated_at: new Date() },
            { nama: 'Sumber Rejo', kecamatan_id: 2, created_at: new Date(), updated_at: new Date() },
            { nama: 'Banjar Rejo', kecamatan_id: 2, created_at: new Date(), updated_at: new Date() },
            { nama: 'Bumi Harjo', kecamatan_id: 2, created_at: new Date(), updated_at: new Date() },
            { nama: 'Bale Rejo', kecamatan_id: 2, created_at: new Date(), updated_at: new Date() },
            { nama: 'Batang Harjo', kecamatan_id: 2, created_at: new Date(), updated_at: new Date() },
            { nama: 'Bumi Mas', kecamatan_id: 2, created_at: new Date(), updated_at: new Date() },
            { nama: 'Selo Rejo', kecamatan_id: 2, created_at: new Date(), updated_at: new Date() },
            { nama: 'Sri Basuki', kecamatan_id: 2, created_at: new Date(), updated_at: new Date() },
            { nama: 'Sumber Agung', kecamatan_id: 2, created_at: new Date(), updated_at: new Date() },
            { nama: 'Purwodadi Mekar', kecamatan_id: 2, created_at: new Date(), updated_at: new Date() },

            { nama: 'Sidomukti', kecamatan_id: 3, created_at: new Date(), updated_at: new Date() },
            { nama: 'Karya Mukti', kecamatan_id: 3, created_at: new Date(), updated_at: new Date() },
            { nama: 'Sidomulyo', kecamatan_id: 3, created_at: new Date(), updated_at: new Date() },
            { nama: 'Sidodadi', kecamatan_id: 3, created_at: new Date(), updated_at: new Date() },
            { nama: 'Trimulyo', kecamatan_id: 3, created_at: new Date(), updated_at: new Date() },
            { nama: 'Girikarto', kecamatan_id: 3, created_at: new Date(), updated_at: new Date() },
            { nama: 'Hargomulyo', kecamatan_id: 3, created_at: new Date(), updated_at: new Date() },
            { nama: 'Wonokarto', kecamatan_id: 3, created_at: new Date(), updated_at: new Date() },
            { nama: 'Suko Harjo', kecamatan_id: 3, created_at: new Date(), updated_at: new Date() },
            { nama: 'Giri Kelopo Mulyo', kecamatan_id: 3, created_at: new Date(), updated_at: new Date() },
            { nama: 'Sumber Gede', kecamatan_id: 3, created_at: new Date(), updated_at: new Date() },
            { nama: 'Sambikarto', kecamatan_id: 3, created_at: new Date(), updated_at: new Date() },
            { nama: 'Sumbersari', kecamatan_id: 3, created_at: new Date(), updated_at: new Date() },
            { nama: 'Mekar Mulya', kecamatan_id: 3, created_at: new Date(), updated_at: new Date() },
            { nama: 'Mekar Mukti', kecamatan_id: 3, created_at: new Date(), updated_at: new Date() },
            { nama: 'Jadi Mulyo', kecamatan_id: 3, created_at: new Date(), updated_at: new Date() },
            { nama: 'Mekar Sari', kecamatan_id: 3, created_at: new Date(), updated_at: new Date() },

            { nama: 'Jaya Guna', kecamatan_id: 4, created_at: new Date(), updated_at: new Date() },
            { nama: 'Sukaraja Tiga', kecamatan_id: 4, created_at: new Date(), updated_at: new Date() },
            { nama: 'Gedung Wani', kecamatan_id: 4, created_at: new Date(), updated_at: new Date() },
            { nama: 'Gedung Wani Timur', kecamatan_id: 4, created_at: new Date(), updated_at: new Date() },
            { nama: 'Surya Mataram', kecamatan_id: 4, created_at: new Date(), updated_at: new Date() },
            { nama: 'Nabang Baru', kecamatan_id: 4, created_at: new Date(), updated_at: new Date() },
            { nama: 'Negeri Jemanten', kecamatan_id: 4, created_at: new Date(), updated_at: new Date() },
            { nama: 'Negeri Agung', kecamatan_id: 4, created_at: new Date(), updated_at: new Date() },
            { nama: 'Negeri Katon', kecamatan_id: 4, created_at: new Date(), updated_at: new Date() },
            { nama: 'Sukadana Baru', kecamatan_id: 4, created_at: new Date(), updated_at: new Date() },
            { nama: 'Tanjung Harapan', kecamatan_id: 4, created_at: new Date(), updated_at: new Date() },
            { nama: 'Negeri Tua', kecamatan_id: 4, created_at: new Date(), updated_at: new Date() },
            { nama: 'Tri Sinar', kecamatan_id: 4, created_at: new Date(), updated_at: new Date() },

            { nama: 'Gunung Agung', kecamatan_id: 5, created_at: new Date(), updated_at: new Date() },
            { nama: 'Gunung Pasir Jaya', kecamatan_id: 5, created_at: new Date(), updated_at: new Date() },
            { nama: 'Gunung Sugih Besar', kecamatan_id: 5, created_at: new Date(), updated_at: new Date() },
            { nama: 'Bauh Gunung Sari', kecamatan_id: 5, created_at: new Date(), updated_at: new Date() },
            { nama: 'Brawijaya', kecamatan_id: 5, created_at: new Date(), updated_at: new Date() },
            { nama: 'Sidorejo', kecamatan_id: 5, created_at: new Date(), updated_at: new Date() },
            { nama: 'Pugung Raharjo', kecamatan_id: 5, created_at: new Date(), updated_at: new Date() },
            { nama: 'Bojong', kecamatan_id: 5, created_at: new Date(), updated_at: new Date() },
            { nama: 'Banjar Agung', kecamatan_id: 5, created_at: new Date(), updated_at: new Date() },
            { nama: 'Tuba', kecamatan_id: 5, created_at: new Date(), updated_at: new Date() },
            { nama: 'Mengandung Sari', kecamatan_id: 5, created_at: new Date(), updated_at: new Date() },
            { nama: 'Sindang Anom', kecamatan_id: 5, created_at: new Date(), updated_at: new Date() },
            { nama: 'Bumi Mulyo', kecamatan_id: 5, created_at: new Date(), updated_at: new Date() },
            { nama: 'Gunung Mulyo', kecamatan_id: 5, created_at: new Date(), updated_at: new Date() },
            { nama: 'Purwo Kencono', kecamatan_id: 5, created_at: new Date(), updated_at: new Date() },

            { nama: 'Mekar Jaya', kecamatan_id: 6, created_at: new Date(), updated_at: new Date() },
            { nama: 'Adirejo', kecamatan_id: 6, created_at: new Date(), updated_at: new Date() },
            { nama: 'Asahan', kecamatan_id: 6, created_at: new Date(), updated_at: new Date() },
            { nama: 'Belimbing Sari', kecamatan_id: 6, created_at: new Date(), updated_at: new Date() },
            { nama: 'Gunung Mekar', kecamatan_id: 6, created_at: new Date(), updated_at: new Date() },
            { nama: 'Benteng Sari', kecamatan_id: 6, created_at: new Date(), updated_at: new Date() },
            { nama: 'Mumbang Jaya', kecamatan_id: 6, created_at: new Date(), updated_at: new Date() },
            { nama: 'Gunung Sugih Kecil', kecamatan_id: 6, created_at: new Date(), updated_at: new Date() },
            { nama: 'Pematang Tahalo', kecamatan_id: 6, created_at: new Date(), updated_at: new Date() },
            { nama: 'Negara Batin', kecamatan_id: 6, created_at: new Date(), updated_at: new Date() },
            { nama: 'Negara Saka', kecamatan_id: 6, created_at: new Date(), updated_at: new Date() },
            { nama: 'Jabung', kecamatan_id: 6, created_at: new Date(), updated_at: new Date() },
            { nama: 'Adi Luhur', kecamatan_id: 6, created_at: new Date(), updated_at: new Date() },
            { nama: 'Tanjung Sari', kecamatan_id: 6, created_at: new Date(), updated_at: new Date() },
            { nama: 'Sambi Rejo', kecamatan_id: 6, created_at: new Date(), updated_at: new Date() },

            { nama: 'Sumur Kucing', kecamatan_id: 7, created_at: new Date(), updated_at: new Date() },
            { nama: 'Labuhan Ratu', kecamatan_id: 7, created_at: new Date(), updated_at: new Date() },
            { nama: 'Kedung Ringin', kecamatan_id: 7, created_at: new Date(), updated_at: new Date() },
            { nama: 'Rejo Mulyo', kecamatan_id: 7, created_at: new Date(), updated_at: new Date() },
            { nama: 'Purworejo', kecamatan_id: 7, created_at: new Date(), updated_at: new Date() },
            { nama: 'Mulyo Sari', kecamatan_id: 7, created_at: new Date(), updated_at: new Date() },
            { nama: 'Pasir Sakti', kecamatan_id: 7, created_at: new Date(), updated_at: new Date() },
            { nama: 'Mekar Sari', kecamatan_id: 7, created_at: new Date(), updated_at: new Date() },

            { nama: 'Marga Batin', kecamatan_id: 8, created_at: new Date(), updated_at: new Date() },
            { nama: 'Sido Rahayu', kecamatan_id: 8, created_at: new Date(), updated_at: new Date() },
            { nama: 'Ngesti Karya', kecamatan_id: 8, created_at: new Date(), updated_at: new Date() },
            { nama: 'Sumber Jaya', kecamatan_id: 8, created_at: new Date(), updated_at: new Date() },
            { nama: 'Sumber Rejo', kecamatan_id: 8, created_at: new Date(), updated_at: new Date() },
            { nama: 'Mekar Karya', kecamatan_id: 8, created_at: new Date(), updated_at: new Date() },
            { nama: 'Tanjung Wangi', kecamatan_id: 8, created_at: new Date(), updated_at: new Date() },
            { nama: 'Tri Tunggal', kecamatan_id: 8, created_at: new Date(), updated_at: new Date() },
            { nama: 'Jembrana', kecamatan_id: 8, created_at: new Date(), updated_at: new Date() },
            { nama: 'Karang Anom', kecamatan_id: 8, created_at: new Date(), updated_at: new Date() },
            { nama: 'Karya Basuki', kecamatan_id: 8, created_at: new Date(), updated_at: new Date() },

            { nama: 'Bungkuk', kecamatan_id: 9, created_at: new Date(), updated_at: new Date() },
            { nama: 'Giri Mulyo', kecamatan_id: 9, created_at: new Date(), updated_at: new Date() },
            { nama: 'Gunung Mas', kecamatan_id: 9, created_at: new Date(), updated_at: new Date() },
            { nama: 'Batu Badak', kecamatan_id: 9, created_at: new Date(), updated_at: new Date() },
            { nama: 'Peniangan', kecamatan_id: 9, created_at: new Date(), updated_at: new Date() },
            { nama: 'Purwosari', kecamatan_id: 9, created_at: new Date(), updated_at: new Date() },
            { nama: 'Gunung Raya', kecamatan_id: 9, created_at: new Date(), updated_at: new Date() },
            { nama: 'Bukit Raya', kecamatan_id: 9, created_at: new Date(), updated_at: new Date() },

            { nama: 'Karyatani', kecamatan_id: 10, created_at: new Date(), updated_at: new Date() },
            { nama: 'Karya Makmur', kecamatan_id: 10, created_at: new Date(), updated_at: new Date() },
            { nama: 'Bandar Negeri', kecamatan_id: 10, created_at: new Date(), updated_at: new Date() },
            { nama: 'Maringgai', kecamatan_id: 10, created_at: new Date(), updated_at: new Date() },
            { nama: 'Muara Gading Mas', kecamatan_id: 10, created_at: new Date(), updated_at: new Date() },
            { nama: 'Labuhan Maringai', kecamatan_id: 10, created_at: new Date(), updated_at: new Date() },
            { nama: 'Sri Gading', kecamatan_id: 10, created_at: new Date(), updated_at: new Date() },
            { nama: 'Sri Minosari', kecamatan_id: 10, created_at: new Date(), updated_at: new Date() },
            { nama: 'Margasari', kecamatan_id: 10, created_at: new Date(), updated_at: new Date() },
            { nama: 'Sukorahayu', kecamatan_id: 10, created_at: new Date(), updated_at: new Date() },
            { nama: 'Karang Anyar', kecamatan_id: 10, created_at: new Date(), updated_at: new Date() },

            { nama: 'Tulungpasik', kecamatan_id: 11, created_at: new Date(), updated_at: new Date() },
            { nama: 'Mandala Sari', kecamatan_id: 11, created_at: new Date(), updated_at: new Date() },
            { nama: 'Kebon Damar', kecamatan_id: 11, created_at: new Date(), updated_at: new Date() },
            { nama: 'Mataram Baru', kecamatan_id: 11, created_at: new Date(), updated_at: new Date() },
            { nama: 'Rajabasa Baru', kecamatan_id: 11, created_at: new Date(), updated_at: new Date() },
            { nama: 'Teluk Dalem', kecamatan_id: 11, created_at: new Date(), updated_at: new Date() },
            { nama: 'Wai Arang', kecamatan_id: 11, created_at: new Date(), updated_at: new Date() },

            { nama: 'Waringin Jaya', kecamatan_id: 12, created_at: new Date(), updated_at: new Date() },
            { nama: 'Sri Bawono', kecamatan_id: 12, created_at: new Date(), updated_at: new Date() },
            { nama: 'Sri Menanti', kecamatan_id: 12, created_at: new Date(), updated_at: new Date() },
            { nama: 'Sri Pendowo', kecamatan_id: 12, created_at: new Date(), updated_at: new Date() },
            { nama: 'Bandar Agung', kecamatan_id: 12, created_at: new Date(), updated_at: new Date() },
            { nama: 'Sadar Sriwijaya', kecamatan_id: 12, created_at: new Date(), updated_at: new Date() },
            { nama: 'Mekar Jaya', kecamatan_id: 12, created_at: new Date(), updated_at: new Date() },

            { nama: 'Sidomakmur', kecamatan_id: 13, created_at: new Date(), updated_at: new Date() },
            { nama: 'Tanjung Aji', kecamatan_id: 13, created_at: new Date(), updated_at: new Date() },
            { nama: 'Tebing', kecamatan_id: 13, created_at: new Date(), updated_at: new Date() },
            { nama: 'Wana', kecamatan_id: 13, created_at: new Date(), updated_at: new Date() },
            { nama: 'Sumberhadi', kecamatan_id: 13, created_at: new Date(), updated_at: new Date() },
            { nama: 'Itik Rendai', kecamatan_id: 13, created_at: new Date(), updated_at: new Date() },

            { nama: 'Negeri Agung', kecamatan_id: 14, created_at: new Date(), updated_at: new Date() },
            { nama: 'Pempen', kecamatan_id: 14, created_at: new Date(), updated_at: new Date() },
            { nama: 'Pelindung Jaya', kecamatan_id: 14, created_at: new Date(), updated_at: new Date() },
            { nama: 'Wai Mili', kecamatan_id: 14, created_at: new Date(), updated_at: new Date() },
            { nama: 'Nibung', kecamatan_id: 14, created_at: new Date(), updated_at: new Date() },

            { nama: 'Braja Fajar', kecamatan_id: 15, created_at: new Date(), updated_at: new Date() },
            { nama: 'Braja Emas', kecamatan_id: 15, created_at: new Date(), updated_at: new Date() },
            { nama: 'Braja Caka', kecamatan_id: 15, created_at: new Date(), updated_at: new Date() },
            { nama: 'Braja Dewa', kecamatan_id: 15, created_at: new Date(), updated_at: new Date() },
            { nama: 'Sri Wangi', kecamatan_id: 15, created_at: new Date(), updated_at: new Date() },
            { nama: 'Jepara', kecamatan_id: 15, created_at: new Date(), updated_at: new Date() },
            { nama: 'Sumberjo', kecamatan_id: 15, created_at: new Date(), updated_at: new Date() },
            { nama: 'Sri Rejosari', kecamatan_id: 15, created_at: new Date(), updated_at: new Date() },
            { nama: 'Labuhan Ratu Dua', kecamatan_id: 15, created_at: new Date(), updated_at: new Date() },
            { nama: 'Sumur Bandung', kecamatan_id: 15, created_at: new Date(), updated_at: new Date() },
            { nama: 'Labuhan Ratu Satu', kecamatan_id: 15, created_at: new Date(), updated_at: new Date() },
            { nama: 'Braja Sakti', kecamatan_id: 15, created_at: new Date(), updated_at: new Date() },
            { nama: 'Braja Asri', kecamatan_id: 15, created_at: new Date(), updated_at: new Date() },
            { nama: 'Sumber Marga', kecamatan_id: 15, created_at: new Date(), updated_at: new Date() },
            { nama: 'Labuhan Ratu Danau', kecamatan_id: 15, created_at: new Date(), updated_at: new Date() },
            { nama: 'Labuhan Ratu Baru', kecamatan_id: 15, created_at: new Date(), updated_at: new Date() },

            { nama: 'Braja Gemilang', kecamatan_id: 16, created_at: new Date(), updated_at: new Date() },
            { nama: 'Braja Luhur', kecamatan_id: 16, created_at: new Date(), updated_at: new Date() },
            { nama: 'Braja Kencana', kecamatan_id: 16, created_at: new Date(), updated_at: new Date() },
            { nama: 'Braja Harjosari', kecamatan_id: 16, created_at: new Date(), updated_at: new Date() },
            { nama: 'Braja Indah', kecamatan_id: 16, created_at: new Date(), updated_at: new Date() },
            { nama: 'Braja Yekti', kecamatan_id: 16, created_at: new Date(), updated_at: new Date() },
            { nama: 'Braja Mulya', kecamatan_id: 16, created_at: new Date(), updated_at: new Date() },

            { nama: 'Labuhan Ratu Empat', kecamatan_id: 17, created_at: new Date(), updated_at: new Date() },
            { nama: 'Labuhan Ratu Lima', kecamatan_id: 17, created_at: new Date(), updated_at: new Date() },
            { nama: 'Labuhan Ratu Tiga', kecamatan_id: 17, created_at: new Date(), updated_at: new Date() },
            { nama: 'Labuhan Ratu VII', kecamatan_id: 17, created_at: new Date(), updated_at: new Date() },
            { nama: 'Labuhan Ratu', kecamatan_id: 17, created_at: new Date(), updated_at: new Date() },
            { nama: 'Labuhan Ratu Enam', kecamatan_id: 17, created_at: new Date(), updated_at: new Date() },
            { nama: 'Raja Basa Lama', kecamatan_id: 17, created_at: new Date(), updated_at: new Date() },
            { nama: 'Raja Basa Lama Satu', kecamatan_id: 17, created_at: new Date(), updated_at: new Date() },
            { nama: 'Raja Basa Lama Dua', kecamatan_id: 17, created_at: new Date(), updated_at: new Date() },
            { nama: 'Labuhan Ratu VIII', kecamatan_id: 17, created_at: new Date(), updated_at: new Date() },
            { nama: 'Labuhan Ratu IX', kecamatan_id: 17, created_at: new Date(), updated_at: new Date() },

            { nama: 'Raja Basa Batanghari', kecamatan_id: 18, created_at: new Date(), updated_at: new Date() },
            { nama: 'Sukadana', kecamatan_id: 18, created_at: new Date(), updated_at: new Date() },
            { nama: 'Putra Aji Dua', kecamatan_id: 18, created_at: new Date(), updated_at: new Date() },
            { nama: 'Pakuan Aji', kecamatan_id: 18, created_at: new Date(), updated_at: new Date() },
            { nama: 'Bumi Nabung Udik', kecamatan_id: 18, created_at: new Date(), updated_at: new Date() },
            { nama: 'Sukadana Timur', kecamatan_id: 18, created_at: new Date(), updated_at: new Date() },
            { nama: 'Surabaya Udik', kecamatan_id: 18, created_at: new Date(), updated_at: new Date() },
            { nama: 'Rantau Jaya Udik II', kecamatan_id: 18, created_at: new Date(), updated_at: new Date() },
            { nama: 'Muara Jaya', kecamatan_id: 18, created_at: new Date(), updated_at: new Date() },
            { nama: 'Rantau Jaya Udik', kecamatan_id: 18, created_at: new Date(), updated_at: new Date() },
            { nama: 'Pasar Sukadana', kecamatan_id: 18, created_at: new Date(), updated_at: new Date() },
            { nama: 'Mataram Marga', kecamatan_id: 18, created_at: new Date(), updated_at: new Date() },
            { nama: 'Terbanggi Marga', kecamatan_id: 18, created_at: new Date(), updated_at: new Date() },
            { nama: 'Sukadana Ilir', kecamatan_id: 18, created_at: new Date(), updated_at: new Date() },
            { nama: 'Negara Nabung', kecamatan_id: 18, created_at: new Date(), updated_at: new Date() },
            { nama: 'Bumi Ayu', kecamatan_id: 18, created_at: new Date(), updated_at: new Date() },
            { nama: 'Putra Aji I', kecamatan_id: 18, created_at: new Date(), updated_at: new Date() },
            { nama: 'Sukadana Selatan', kecamatan_id: 18, created_at: new Date(), updated_at: new Date() },
            { nama: 'Sukadana Tengah', kecamatan_id: 18, created_at: new Date(), updated_at: new Date() },
            { nama: 'Sukadana Jaya', kecamatan_id: 18, created_at: new Date(), updated_at: new Date() },

            { nama: 'Marga Mulya', kecamatan_id: 19, created_at: new Date(), updated_at: new Date() },
            { nama: 'Donomulyo', kecamatan_id: 19, created_at: new Date(), updated_at: new Date() },
            { nama: 'Nyampir', kecamatan_id: 19, created_at: new Date(), updated_at: new Date() },
            { nama: 'Bumi Tinggi', kecamatan_id: 19, created_at: new Date(), updated_at: new Date() },
            { nama: 'Lehan', kecamatan_id: 19, created_at: new Date(), updated_at: new Date() },
            { nama: 'Catur Swako', kecamatan_id: 19, created_at: new Date(), updated_at: new Date() },
            { nama: 'Mulyo Asri', kecamatan_id: 19, created_at: new Date(), updated_at: new Date() },

            { nama: 'Gunung Tiga', kecamatan_id: 20, created_at: new Date(), updated_at: new Date() },
            { nama: 'Sukacari', kecamatan_id: 20, created_at: new Date(), updated_at: new Date() },
            { nama: 'Negara Ratu', kecamatan_id: 20, created_at: new Date(), updated_at: new Date() },
            { nama: 'Bumi Jawa', kecamatan_id: 20, created_at: new Date(), updated_at: new Date() },
            { nama: 'Gedung Dalam', kecamatan_id: 20, created_at: new Date(), updated_at: new Date() },
            { nama: 'Sukaraja Nuban', kecamatan_id: 20, created_at: new Date(), updated_at: new Date() },
            { nama: 'Trisno Mulyo', kecamatan_id: 20, created_at: new Date(), updated_at: new Date() },
            { nama: 'Cempaka Nuban', kecamatan_id: 20, created_at: new Date(), updated_at: new Date() },
            { nama: 'Kedaton II (Dua)', kecamatan_id: 20, created_at: new Date(), updated_at: new Date() },
            { nama: 'Kedaton Induk', kecamatan_id: 20, created_at: new Date(), updated_at: new Date() },
            { nama: 'Kedaton I (Satu)', kecamatan_id: 20, created_at: new Date(), updated_at: new Date() },
            { nama: 'Tulung Balak', kecamatan_id: 20, created_at: new Date(), updated_at: new Date() },
            { nama: 'Purwosari', kecamatan_id: 20, created_at: new Date(), updated_at: new Date() },

            { nama: 'Adirejo', kecamatan_id: 21, created_at: new Date(), updated_at: new Date() },
            { nama: 'Sidodadi', kecamatan_id: 21, created_at: new Date(), updated_at: new Date() },
            { nama: 'Gondang Rejo', kecamatan_id: 21, created_at: new Date(), updated_at: new Date() },
            { nama: 'Siraman', kecamatan_id: 21, created_at: new Date(), updated_at: new Date() },
            { nama: 'Pekalongan', kecamatan_id: 21, created_at: new Date(), updated_at: new Date() },
            { nama: 'Tulus Rejo', kecamatan_id: 21, created_at: new Date(), updated_at: new Date() },
            { nama: 'Jojog', kecamatan_id: 21, created_at: new Date(), updated_at: new Date() },
            { nama: 'Ganti Warno', kecamatan_id: 21, created_at: new Date(), updated_at: new Date() },
            { nama: 'Kali Bening', kecamatan_id: 21, created_at: new Date(), updated_at: new Date() },
            { nama: 'Wono Sari', kecamatan_id: 21, created_at: new Date(), updated_at: new Date() },
            { nama: 'Adijaya', kecamatan_id: 21, created_at: new Date(), updated_at: new Date() },
            { nama: 'Gantimulyo', kecamatan_id: 21, created_at: new Date(), updated_at: new Date() },

            { nama: 'Raman Aji', kecamatan_id: 22, created_at: new Date(), updated_at: new Date() },
            { nama: 'Rukti Sediyoo', kecamatan_id: 22, created_at: new Date(), updated_at: new Date() },
            { nama: 'Ratna Daya', kecamatan_id: 22, created_at: new Date(), updated_at: new Date() },
            { nama: 'Kota Raman', kecamatan_id: 22, created_at: new Date(), updated_at: new Date() },
            { nama: 'Rejo Binangun', kecamatan_id: 22, created_at: new Date(), updated_at: new Date() },
            { nama: 'Rantau Fajar', kecamatan_id: 22, created_at: new Date(), updated_at: new Date() },
            { nama: 'Raman Endra', kecamatan_id: 22, created_at: new Date(), updated_at: new Date() },
            { nama: 'Raman Fajar', kecamatan_id: 22, created_at: new Date(), updated_at: new Date() },
            { nama: 'Restu Rahayu', kecamatan_id: 22, created_at: new Date(), updated_at: new Date() },
            { nama: 'Rejo Katon', kecamatan_id: 22, created_at: new Date(), updated_at: new Date() },
            { nama: 'Rama Puja', kecamatan_id: 22, created_at: new Date(), updated_at: new Date() },

            { nama: 'Taman Asri', kecamatan_id: 23, created_at: new Date(), updated_at: new Date() },
            { nama: 'Taman Bogo', kecamatan_id: 23, created_at: new Date(), updated_at: new Date() },
            { nama: 'Tambah Dadi', kecamatan_id: 23, created_at: new Date(), updated_at: new Date() },
            { nama: 'Taman Cari', kecamatan_id: 23, created_at: new Date(), updated_at: new Date() },
            { nama: 'Taman Endah', kecamatan_id: 23, created_at: new Date(), updated_at: new Date() },
            { nama: 'Taman Fajar', kecamatan_id: 23, created_at: new Date(), updated_at: new Date() },
            { nama: 'Tegal Gondo', kecamatan_id: 23, created_at: new Date(), updated_at: new Date() },
            { nama: 'Toto Harjo', kecamatan_id: 23, created_at: new Date(), updated_at: new Date() },
            { nama: 'Tambah Luhur', kecamatan_id: 23, created_at: new Date(), updated_at: new Date() },
            { nama: 'Tanjung Inten', kecamatan_id: 23, created_at: new Date(), updated_at: new Date() },
            { nama: 'Tegal Yoso', kecamatan_id: 23, created_at: new Date(), updated_at: new Date() },
            { nama: 'Tanjung Kesuma', kecamatan_id: 23, created_at: new Date(), updated_at: new Date() },

            { nama: 'Toto Mulyo', kecamatan_id: 24, created_at: new Date(), updated_at: new Date() },
            { nama: 'Tegal Ombo', kecamatan_id: 24, created_at: new Date(), updated_at: new Date() },
            { nama: 'Toto Projo', kecamatan_id: 24, created_at: new Date(), updated_at: new Date() },
            { nama: 'Taman Negeri', kecamatan_id: 24, created_at: new Date(), updated_at: new Date() },
            { nama: 'Tanjung Kencono', kecamatan_id: 24, created_at: new Date(), updated_at: new Date() },
            { nama: 'Tambah Subur', kecamatan_id: 24, created_at: new Date(), updated_at: new Date() },
            { nama: 'Tanjung Tirto', kecamatan_id: 24, created_at: new Date(), updated_at: new Date() },
            { nama: 'Kali Pasir', kecamatan_id: 24, created_at: new Date(), updated_at: new Date() }
        ];

        await queryInterface.bulkInsert({ tableName: "master_desa" }, desa, {});
    },

    async down(queryInterface, Sequelize) {
        /**
         * Add commands to revert seed here.
         *
         * Example:
         * await queryInterface.bulkDelete('People', null, {});
         */
        await queryInterface.bulkDelete({ tableName: "master_desa" }, null, {});
    }
};
