# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI CD sitani-backend

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Git pull
      run: |
          cd /home/newus-backend-sitani/htdocs/backend-sitani.newus.id
          git pull
    - name: Run migration if present
      run: |
          cd /home/newus-backend-sitani/htdocs/backend-sitani.newus.id
          npx sequelize-cli db:migrate
    - name: Run NPM
      run: npm ci
    - name : restart PM2
      run : |
          APP_NAME="backend-sitani.newus.id"
          APP_ID="15"

          if pm2 restart $APP_NAME; then
            echo "Successfully restarted app with name $APP_NAME"
          else
            echo "Failed to restart app with name $APP_NAME, trying with ID $APP_ID"
            if pm2 restart $APP_ID; then
              echo "Successfully restarted app with ID $APP_ID"
            else
              echo "Failed to restart app with both name and ID"
              exit 1
            fi
          fi
